### ISSUE TITLE
Can't set headers w/ next(new BedrockError(...))

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-views#1]
When creating a new BedrockError, it's not easy to set the headers in the response object.

Perhaps we should have something similar to BedrockError.details.httpStatusCode that is a list of headers to set when handling unknown errors?

**Comment by dlongley** [comment]
Adding custom headers to an error may be at the wrong level of abstraction (though maybe it would also be ok). Right now, you should be able to simply set the headers, for example, on an express response and then let the error pass through to an error handler. I don't believe any of the custom headers set would be cleared.

**Comment by dlongley** [comment]
Closing this for now. It seems like we have a mechanism for doing this that is at a reasonable level of abstraction.
