### ISSUE TITLE
requests for unknown static resources should return 404

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-views#10]
Currently if you request an unknown resource from a directory configured to serve static resources you will get back a 200 with main.html content.  This can cause unexpected failures for requests.  https://github.com/digitalbazaar/bedrock-express may also be involved in this behavior.

Test with simple request:
`curl -vk -H "Accept: application/json" https://example.com/staticdir/bogus.json`

**Comment by dlongley** [comment]
Desired behavior should be to get a 404 status code if the path is a static path. May just need to call `res.status(404)` in `bedrock-express` in the static handler code and then let later handlers either clear it/change it or leave it.

**Comment by dlongley** [comment]
Addressed by https://github.com/digitalbazaar/bedrock-express/commit/edac750249534d6d4f582d276ad67904dafdbe89 and https://github.com/digitalbazaar/bedrock-express/commit/6a9af52bc3f0ac25d23be462377c6f0d8b0d0d93.
