### ISSUE TITLE
Replace "view vars" with a frontend config call

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-views#14]
We should do our best to eliminate "view vars" as much as possible, because:

1. It's use is confusing.
2. It's unnecessary/awkward to inject config into the page to be read by the client application and there are simpler/better ways of getting backend config information.
3. It's overly complex with having to use hooks to add config vars at the right time and so on (computed config solves this problem in a better way).
4. It's unclear to devs what should be in view vars and what should be provided some other way.

It makes sense to provide endpoint information about services via a config that the frontend can access. We should, however, make a call to the backend to retrieve this instead of serializing some vars as JSON into the page and then reading them out. We already have conventions for discovering service endpoints for servers and we should make our frontend application reuse those for the backend it's tied to.

That means that the frontend should hit `/` and retrieve JSON-LD information about the backend. That information should include all of the service endpoints it needs to use (or links to get at that information through follow-your-nose). This is where "view vars" should move to. We should try to eliminate everything else in "view vars", pushing it to frontend configuration, or if absolutely necessary, expose it through other configuration endpoints on the server. Ideally, it would all be frontend-driven if it's not information that specifically pertains to backend service locations.

cc: @msporny, @davidlehn, @mattcollier, @markcherbaka

**Comment by msporny** [comment]
Fine with making this change, I just need an example to follow. 

At some point we were also considering exposing all services that a site provides via the landing page (embedded JSON-LD) or a /.well-known/http-services endpoint (that serves JSON-LD). Why don't we switch to that for variables too? /.well-known/site-config? ... and then have some config service that dumps the necessary information in there? Perhaps we can have an event that effectively replaces the view.vars event (forget what it's called) that basically notifies each module "hey, if you want to expose something to the site config or the http-services endpoint, now's the time to do it - put it in this config variable.

**Comment by msporny** [comment]
For example:

```javascript
// setup service endpoints available via /.well-known/http-services
bedrock.events.on('bedrock-http-services.config.set', (config, callback) => {
  config.userJoinService = bedrock.config.baseUri + vars['website-user-http'].basePath;
  callback();
});

// setup site variables available via /.well-known/site-config
bedrock.events.on('bedrock-site.config.set', (config, callback) => {
  let cfg = config['identity-http'] = {}
  cfg.basePath = bedrock.config['identity-http'].basePath;
  cfg.baseUri = bedrock.config.baseUri + vars['identity-http'].basePath;
  callback();
});
```

**Comment by davidlehn** [comment]
What are the effects of a fully dynamic configuration step on performance?  We'd like to reduce blocking round trips if possible.

**Comment by dlongley** [comment]
@msporny,

> At some point we were also considering exposing all services that a site provides via the landing page (embedded JSON-LD) or a /.well-known/http-services endpoint (that serves JSON-LD). Why don't we switch to that for variables too? /.well-known/site-config?

That's what I'm talking about. It may be that all we need for the frontend, however, is the services, so there's no need to add anything beyond that. In any event, if we end up adding any sort of access to config, I would expect that what you'd do would be:

1. Get the services endpoints config doc.
2. Use the config service endpoint in the doc to get the config.

> Perhaps we can have an event that effectively replaces the view.vars event (forget what it's called) that basically notifies each module "hey, if you want to expose something to the site config or the http-services endpoint, now's the time to do it - put it in this config variable.

We already do that with the `addViewVars` event. We don't want to do that at all, I don't think. Rather, we would have some `bedrock.config['config-http']` config or something that you could just append computed configs to.

In a config-http thing's config:

```js
bedrock.config['config-http'].routes.basePath = '/';
// could also add some .well-known endpoint too if we want
```

Then in a config-http thing's index:

```js
bedrock.events.on('bedrock-express.config.routes', app => {
  app.get(bedrock.config['config-http'].routes.basePath, (req, res, next) => {
    res.json(bedrock.config['config-http']);
  });
```

Then in my-module's config:

```js
const cc = bedrock.config.main;
cc('config-http.my-module.foo', () =>
  bedrock.config.baseUri + bedrock.config['my-module'].basePath);
```

I'm not saying we should do exactly that^, just brainstorming.

**Comment by dlongley** [comment]
@davidlehn,

> What are the effects of a fully dynamic configuration step on performance? We'd like to reduce blocking round trips if possible.

We can find a solution to deal with this, but it's a second order concern, IMO.

**Comment by dlongley** [comment]
We can probably be fetching the site config at the same time we're fetching the main requirejs config.

**Comment by dlongley** [comment]
We might want not want to make this `bedrock.config.config-http` since it's so protocol-centric, we just need a better name for building up the config "document that describes the site/node/application/thing" and then exposing it via http is just one way (the only way for now) to get at that site description document.

**Comment by dlongley** [comment]
Also worth noting that the new (2017/05/30) SystemJS config is currently served up as a JS file that runs `SystemJS.config()` ... instead a web call to fetch the whole frontend config could be followed with one to run that command manually, allowing easier frontend adjustments to the config prior to calling it.

**Comment by dlongley** [comment]
Frontend configs have been implemented and view vars are no longer used, closing.
