### ISSUE TITLE
Handling packages that are not actual dependencies

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-views#25]
In bedrock-angular-bootstrap, we have a manifest override for `jquery` here:

https://github.com/digitalbazaar/bedrock-angular-bootstrap/blob/master/package.json#L27

The issue is, that if `jquery` is never actually specified as a dependency in any module, then that override passes through the front-end module loading process as a zombie package that looks like this:
```
{
  browser: false
}
```

One of the first evidence of failure is this line:
https://github.com/digitalbazaar/bedrock-views/blob/master/lib/commands.js#L137

Which is run during compile-less which throws an error that `pkg.findMainFiles` is not a function.  If one does a workaround for this particular issue, compile-less just hangs somewhere down the line.

This issue can easily be demonstrated by installing this example module: https://github.com/digitalbazaar/bedrock-examples/tree/es6/advanced-skin

At the moment, an unnecessary `jquery` dependency has been added to allow the override process to work properly.  If that jquery dependency is removed, the errors mentioned above will become evident.

Somehow overrides for non-existent modules need to be eliminated.

**Comment by dlongley** [comment]
Addressed by 578b16b710476fbf7446466f3f4174833716896a.
