### ISSUE TITLE
SystemJS and Safari

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-views#27]
here is the main.js
```
/* global SystemJS */
(async function() {

// configure SystemJS
await SystemJS.import('system/app/config.js');

// load all detected modules
await SystemJS.import('importAll');

// start angular app
const bedrock = await SystemJS.import('bedrock-angular');
bedrock.start();

})();
```
Safari (v9 and v10) are throwing unexpected keyword 'function', expected ')' to end a compound expression.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

Support for `async` was added to Safari in v10.1 released March 27, 2017

Safari 10.0 is the latest version available to us on SauceLabs for E2E testing.

Video of error message available here: https://saucelabs.com/beta/tests/c215c8d78cc3455faf540dab6db70881/watch

**Comment by dlongley** [comment]
I vote that this is a "won't fix". Our multi-browser automated tests should be tested against the webpacked code (transpiled and minified code) which would make this a non-issue. That's the stuff we will be pushing into production anyway.

**Comment by mattcollier** [comment]
We are proceeding with using minified code for our cross-browser testing.
