### ISSUE TITLE
`js` extension on front end imports

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-views#28]
When we did the systemjs upgrade, we explicitly added `.js` extension to all the import statements as here: https://github.com/digitalbazaar/bedrock-angular-authn-password/blob/master/index.js#L5

It appears that this is not a *requirement* because the imports are working properly here:
https://github.com/digitalbazaar/bedrock-angular-entity/blob/implementation/index.js#L5

Do we continue to add `.js` to imports by convention, or update the convention and start omitting the `.js` extension?

**Comment by davidlehn** [comment]
I thought that was done on purpose?  Maybe webpack does something special, but native module support examples all seem to be using the extension.

**Comment by mattcollier** [comment]
@davidlehn if you `npm install` the `dev` package in bedrock-angular-entity, the imports work in development mode.  The structure of that package does not support optimization, so I don't know what will happen when webpack gets involved.

**Comment by dlongley** [comment]
We should keep using the `.js` extension. That's how all of the examples on the Web work -- and how browsers natively handle it. Omitting it is a bad idea that shouldn't have been done by SystemJS, IMO.

**Comment by dlongley** [comment]
Closing ... use `.js` extension for files, no extension for package names.
