### ISSUE TITLE
`importAll` sorting

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-views#29]
When `bedrock-views` builds the `importAll` file that is used to load all the front end code, modules that do not list any dependencies are sorted to the top.

`angular-material`, `angular-messages` and `angular-wizard` are examples of this.  Here are `package.json` files for [angular-messages](https://gist.github.com/mattcollier/00019688397ffe68e3c37878fe9d1f6a) and [angular-material](https://gist.github.com/mattcollier/6078274f3ca2183933bd5caddf55cf5c)

In order to prevent `angular-messages` from getting sorted to the top of the `importAll` list, and then failing at runtime because `angular` is not loaded, one must add a manifest override wherever `angular-messages` is used.

```json
{
  "bedrock":
    "manifest": {
      "angular-messages": {
        "dependencies": {
          "angular": "~1.6.5"
        }
      },
      "angular-wizard": {
        "dependencies": {
          "angular": "~1.6.5"
        },
        "less": "dist/angular-wizard.less"
      }
    }
  }
}
```

We have precedent  for creating bedrock wrapper modules in order to apply overrides for commonly used modules.  However, this is such a common issue, that I think another solution is in order.  Having to create and maintain these convenience packages is unattractive, and also we will run into namespace issues (if we continue the current convention) with `angular-messages` since we already have `bedrock-angular-messages`.

First, I would like to point out the [JSPM section](https://gist.github.com/mattcollier/00019688397ffe68e3c37878fe9d1f6a#file-package-json-L25-L31) of the `angular-messages` package file.  I've noticed that the `angular*` packages I've looked at all have this section and list `angular` as a dependency there.  Could we make use of this information when available? `angular-material` and `angular-messages` each list their `angular` dependency using different techniques.

If we don't do that, perhaps we should just *always* put `angular` at the top of the `importAll` file.

**Comment by dlongley** [comment]
Let's add support for reading the `jspm` section to resolve this.

**Comment by mattcollier** [comment]
package.json for [angular-aria](https://gist.github.com/mattcollier/bb91d5ef65a22f8ba5277dfc4b1a1c56)

**Comment by dlongley** [comment]
When considering sort order, we should also look at `peerDependencies` at the top level of package.json.

**Comment by dlongley** [comment]
Let's add support for looking at `peerDependencies` (top-level) and `jspm.shim.x.deps`. I don't think we should support `jspm.dependencies` at this time because the entries look like they map to other repos or github, etc. -- and there could potentially be conflicts.

**Comment by dlongley** [comment]
This is no longer used / applicable; closing.
