### ISSUE TITLE
peerDependencies in bedrock-angular-*

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-views#30]
What do people think about this?
https://github.com/digitalbazaar/bedrock-angular-form/blob/peerDeps/package.json

Which works in conjunction with this:
https://github.com/digitalbazaar/bedrock-views/commit/fe974e70efbc09e742de4a09c5e8ac3f74b1c042

I'm thinking it makes sense for the same reason we do it with back-end bedrock modules.

**Comment by dlongley** [comment]
Decided against -- tradeoffs either way, easier for devs to not have to go through an iterative dependency install hell (which happens a lot) vs. less common scenario where peer deps don't match up and things are mysteriously broken.
