### ISSUE TITLE
Fix serving of unprocessed node code.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-views#32]
There is a problem with some packages, such as jsonld, where the system in dev mode tries to serve unprocessed files.  This results in unknown node code in the browser such as require().  A fix is to use the built code via the following in package.json:
```json
  "manifest": {
    "jsonld": {
      "main": "dist/jsonld.min.js"
    }
  }
```
Processing jsonld.js with a tool like webpack would use the browser field to pick the correct `lib/index.js` to use and process the code appropriately.  The bedrock code should somehow do similar or find another solution to avoid needing to specify the above in every project.

**Comment by dlongley** [comment]
This is no longer applicable, closing.
