### ISSUE TITLE
Collapsed navbar margins

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-views#5]
A collapsed navbar does not have the correct margins.  A simple example is the display of login/join buttons which are not centered.  This may be due to the .navbar .btn-toolbar margin-bottom of -13px.  If that is set to 0, the buttons display correctly when collapsed but not when uncollapsed.

Likely another override is needed for the collapsed toolbar.

Also the -13px and similar should be computed in the less file from the navbar height variable.

**Comment by dlongley** [comment]
This issue should be moved to bedrock-angular-navbar along with any relevant CSS so this is a modularized problem+solution.

**Comment by dlongley** [comment]
Won't fix; not supporting angular anymore/belongs in another package.
