### ISSUE TITLE
CSRF cookie name

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-views#59]
7.0.3 removed "XSRF-TOKEN" cookies in favor of csurf package default of "_csrf".
https://github.com/digitalbazaar/bedrock-views/commit/48f7e97c55f7a6b77cdf8246ad53ab8b4e8e47c4
https://github.com/digitalbazaar/bedrock-views/commit/edc795bf4b1060dd9efc0619e451b7e4d6c50bfd

It looks like axios uses a "xsrfCookieName" of "XSRF-TOKEN":
https://github.com/axios/axios

Should the csurf cookie name be changed to"XSRF-TOKEN"?  Or the axios default changed to "_csrf"? Or is this not an issue in our use case?

**Comment by dlongley** [comment]
Let's just change our csurf cookie name to `XSRF-TOKEN`. Should be able to with the `name` option.

**Comment by dlongley** [comment]
We also don't plan on continuing to use axios -- so what does ky/http-client do?

**Comment by dlongley** [comment]
Addressed by #73 (default anti-csrf feature removed).
